### ISSUE TITLE
Cross-compile error for Windows

### ISSUE THREAD

**Issue by netmiller** [paultag/go-ykpiv#11]
I'm trying to build executable for __Win10 platform__, and get errors like:

````
► iMac@ykpiv$ GOOS=windows GOARCH=amd64 go build -o ykls.exe ykls.go
# pault.ag/go/ykpiv
src/pault.ag/go/ykpiv/tls.go:29:12: undefined: Slot
````

Everything is ok when building for darwin:

````
► iMac@ykpiv$ GOOS=darwin GOARCH=amd64 go build -o ykls.osx  ykls.go
````

and it works like charm (standalone). Same when running `go run .....`.

But my main target is Windows-platform, and cross-compiling for windows (within osx) is best for developing my project.  So I need some newbie help !

Maybe I'm missing something : 

* header files (#include <ykpiv.h>)  ??
* dll :s  ??  I have osx __libykcs11.dylib__ in my project root
* some __cgo__ flags ??

Can you help to figure my toolchain for this cross-compile.
Otherwise cross-compiling (osx -> win) is working very well (at least with std.libs).

But __cgo or cross-compiling__ is new to me :(

**Comment by ryandeivert** [comment]
hey @paultag are you able follow up on this at all? I'm also trying to compile for windows and get the same error

**Comment by paultag** [comment]
Hey, I've not. I don't have any Windows machines handy, and I don't have a ton of time. If someone can track down why this is happening, I'd take patches, but I've never spent time getting this working on Windows.

FWIW, the `#cgo` directives in `slot.go` are `#cgo linux` may need to be tweaked or set for Windows, or maybe it's something with regards to not having the Windows `.dll` files. Not sure.

I don't know much about the Windows build toolchains, nor how well cgo cross-compiles work when you're targeting Windows :)

**Comment by netmiller** [comment]
I'm still interested solving this. Now I use Node+Graphene(Electron) for my solution, but it had also some problems with Windows. Better solution for my project would be Golang. Haven't had time to play with this, so @ryandeivert if you have some ideas ...

**Comment by luc-lynx** [comment]
So managed to make it work on Windows, here is a short instruction
https://github.com/luc-lynx/go-ykpiv#running-on-windows

and you must also add the following lines to the `ykpiv.go`:

```
#cgo windows CFLAGS: -I./win/include/ykpiv/
#cgo windows LDFLAGS: ./win/lib/libykpiv.dll.a
```

**Comment by paultag** [comment]
@luc-lynx awsome! I have the change locally; do you want to send a PR I can merge for this or should I just push the lines as is. Thank you for your help!

**Comment by paultag** [comment]
Scratch that I see your Windows commit. I pushed that as 3d7808f34fc02756d50feb404f20bd072d8fafec
