### ISSUE TITLE
Error building: could not determine kind of name for C.ykpiv_attest

### ISSUE THREAD

**Issue by liamg** [paultag/go-ykpiv#16]
I think this may be a compatibility problem between `libykpiv-dev` and this package? I'm using version `1.4.2-2` on Ubuntu 18.04.
```
vendor/pault.ag/go/ykpiv/ykpiv.go:336:21: could not determine kind of name for C.ykpiv_attest
```

**Comment by jtakkala** [comment]
ykpiv_attest() was [introduced in 1.5.0](https://developers.yubico.com/yubico-piv-tool/Release_Notes.html). Looks like you'll need a newer version of yubico-piv-tool, or get Ubuntu to update the package.

**Comment by liamg** [comment]
Okay, thanks for the quick response!
