### ISSUE TITLE
Tag v1.2.0?

### ISSUE THREAD

**Issue by ericchiang** [paultag/go-ykpiv#21]
Go modules are all cool now :) https://github.com/golang/go/wiki/Modules

**Comment by paultag** [comment]
Send a PR adding the go.mod and I'll land it when I have the chance

**Comment by ericchiang** [comment]
You don't actually need a go.mod to work with modules. Just wondering if you wanted to add the tag (I can target a git commit anyway).

I'll send a PR though

**Comment by paultag** [comment]
https://github.com/paultag/go-ykpiv/tree/v1.2.0
